//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuel_Consumption_Analysis.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fuel_Consumption_AnalysisEntities : DbContext
    {
        public Fuel_Consumption_AnalysisEntities()
            : base("name=Fuel_Consumption_AnalysisEntities")
        {
        }

        private static Fuel_Consumption_AnalysisEntities context;

        public static Fuel_Consumption_AnalysisEntities GetContext()
        {
            if (context == null)
                context = new Fuel_Consumption_AnalysisEntities();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Records> Records { get; set; }
    }
}
