//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuel_Consumption_Analysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public string ID { get; set; }
        public System.DateTime Date { get; set; }
        public string CarID { get; set; }
        public double Сonsumption { get; set; }
        public double Distance { get; set; }
        public double Result { get; set; }
    }
}
